### ISSUE TITLE
fails to be built on Manjaro (unknown public key 4A2B758631E1FD91)

### ISSUE THREAD

**Issue by dulhaver** [maximbaz/snap-pac-grub#3]
hi there,

first of all thanks for making `snap-pac-grub` and all. I am using this on a Manjaro Laptop which is being built from `AUR` with `pamac`.

The most recent update fails to build with a reference to the pgp key (_unknown public key 4A2B758631E1FD91_) not being accepted.

```
Building snap-pac-grub...
==> Making package: snap-pac-grub 2.0.0-1 (Fr 17 Jun 2022 09:21:49 CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found snap-pac-grub-2.0.0.tar.gz
  -> Found snap-pac-grub-2.0.0.tar.gz.sig
==> Validating source files with sha256sums...
    snap-pac-grub-2.0.0.tar.gz ... Passed
    snap-pac-grub-2.0.0.tar.gz.sig ... Skipped
==> Verifying source file signatures with gpg...
    snap-pac-grub-2.0.0.tar.gz ... FAILED (unknown public key 4A2B758631E1FD91)
==> ERROR: One or more PGP signatures could not be verified!
Failed to build snap-pac-grub
```

I tried several things in order to get it working, mainly based on [this Topic](https://forum.manjaro.org/t/aur-package-fails-to-verify-pgp-gpg-key-unknown-public-key-one-or-more-pgp-signatures-could-not-be-verified/6663) from the manjaro forum

```
$ rm /var/tmp/pamac/aur-manolo/snap-pac-grub-2.0.0-1/

$ sudo gpg --recv-key 4A2B758631E1FD91

$ sudo gpg --keyserver keys.openpgp.org --recv-key 4A2B758631E1FD91
gpg: key B5DB77409B11B601: "Maxim Baz <pgp@maximbaz.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
```
but none of them had the desired effect (even though the import seems to have been working).

Looking at the [keyfile from your homepage](https://maximbaz.com/pgp_keys.asc) I can not identify any key with the ID pamac is looking for in the build process (4A2B758631E1FD91).

I am not all to versed in AUR and building packages in general, so I may wrong tree here. If that was the case, just close this and I'll try to find a solution elsewhere.

**Comment by max-baz** [comment]
Hi there,

Normally you shouldn't be expected to do anything, because my key is present in `archlinux-keyring` which you surely have installed. But in any case, the trick is either to add `keyserver-options auto-key-retrieve` to your `~/.gnupg/gpg.conf`, or to receive the key (which you correctly guessed to do), but the thing you missed is that you must use the key exactly as it says inside PKGBUILD, i.e. you should have ran `gpg --recv-keys 56C3E775E72B0C8B1C0C1BD0B5DB77409B11B601`.

I'm not exactly sure why you are running it with `sudo` (I'd expect this operation to save the downloaded key in the root user, not in your user), and also the result says that the key is "not changed", meaning you already have it on your computer (probably from `archlinux-keyring`)...

`4A2B758631E1FD91` is a subkey of the main key `56C3E775E72B0C8B1C0C1BD0B5DB77409B11B601`, so when you import the main key and run `gpg -k 56C3E775E72B0C8B1C0C1BD0B5DB77409B11B601`, you will see the `4A2B758631E1FD91` as a subkey with `[S]` flag.

Hope that somewhat helps!

**Comment by dulhaver** [comment]
well, as so often going a little back and forth finally solved it. And you are right about `sudo` (importing the key did not work the first without it). Now ... all went through with

1. `gpg --recv-keys 4A2B758631E1FD91`
2. building the package via pamac

sorry, for the noise
